sudo: false
language: node_js
node_js:
  - stable
script:
  - npm test
before_install:
  - npm i -g makeshift && makeshift -s @datchley -r https://registry.npmjs.org
after_success:
  - npm run report-coverage
deploy:
  provider: npm
  email: david.m.atchley@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: datchley/react-scale-text
